### ISSUE TITLE
Support for ReadOnlyRootFilesystem in Starrocks Chart

### ISSUE THREAD

**Issue by kapilsingh421** [StarRocks/starrocks-kubernetes-operator#390]
## Describe the bug

Enabling ReadOnlyRootFilesystem should be supported.

## To Reproduce

Not able to add ReadOnlyRootFilesystem:true

## Expected behavior

Both the frontend and compute node are expected to function correctly.

The Persistent Volume (PV) paths are set as follows: for the frontend, 
/opt/starrocks/fe/meta and /opt/starrocks/fe/logs. 
The compute node uses a similar configuration with paths at /opt/starrocks/cn/storage and /opt/starrocks/cn/logs.

- Chart Version V1.9.0

**Comment by yandongxiao** [comment]
StarRocks(3.2) now does not support to run on ReadOnly file system. So we can not
set `pod.spec.containers.securityContext.readOnlyRootFilesystem` to true.

In order to run StarRocks on read-only file system, we can do the following steps to work around this issue.

1. Update Dockerfile. Copy the files from the original image to a temporary directory.

```dockerfile
# specific starrocks fe-ubuntu image with the provided sha256 digest
FROM starrocks/fe-ubuntu:3.2-latest

# Set the environment variables for the source and destination directories
ENV STARROCKS_ROOT=/opt/starrocks
ENV STARROCKS_TEMP=/opt/starrocks_temp

RUN mkdir -p $STARROCKS_TEMP && cp -a $STARROCKS_ROOT/. $STARROCKS_TEMP/

# rename the original entrypoint script so it can be executed from the your own script
RUN mv $STARROCKS_TEMP/fe_entrypoint.sh $STARROCKS_ROOT/fe_entrypoint_orig.sh

# copy your own script to the container so it matches what the operator will create for the pod spec.cmd
COPY your-own-entrypoint.sh $STARROCKS_ROOT/fe_entrypoint.sh

# Note: this will make the size of the image larger than the original image
RUN chown -R starrocks:starrocks /opt/starrocks_temp/fe/
```

2. Update entrypoint script. After we mount the persistent volume to the `/opt/starrocks/fe` directory, we can copy the
   files from the temporary directory to the persistent volume mount.

```shell
#!/bin/bash

STARROCKS_TEMP="/opt/starrocks_temp"
STARROCKS_ROOT="/opt/starrocks"

# We will mount a persistent volume to /opt/starrocks/fe
# Copy files from the temporary directory to the persistent volume mount.
# In order to avoid copying files every time, we can check whether the /opt/starrocks/fe is empty or not
if cp -r "$STARROCKS_TEMP"/fe/* "$STARROCKS_ROOT"/fe/; then
    echo "Files copied successfully."
else
    echo "Failed to copy files from $STARROCKS_TEMP to $STARROCKS_ROOT - check permissions and paths."

# execute the original entrypoint script
```
