### ISSUE TITLE
[Enhancement] Re-design the failure and recovery mechanism in k8s environment

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#49]
The failure and recovery mechanism needs to be re-designed for the k8s environment for the following reasons:

1) StarRocks includes a clone process to address missing replicas in situations where the number of alive replicas is insufficient, such as when a BackEnd (BE) node fails. However, in a Kubernetes (k8s) environment, the failure mode of a BE node is different. Specifically, if a BE fails a k8s liveness probe check, which may be due to reasons like VM node failure, the BE will not be permanently dead. Instead, the k8s control plane will schedule the BE on a different VM node in the form of a stateful set pod.

2) Data tablets are not lost when a BE is detected as dead. This is because the data tablets associated with the BE are typically stored in a Persistent Volume that is backed by a separate block storage service, such as EBS or Azure Disk Storage. These block storage services have much higher durability than a commodity disk, and they do not necessarily fail when the BE fails. Consequently, when a BE stateful set pod is rescheduled to a different node, the data tablet will still be available via the Persistent Volume.

3) it is important to note that the end-to-end time that k8s takes to reschedule a new BE might be longer than the 5 minutes threshold that StarRocks uses to consider a BE as dead. Please check the timeline graph of how a pod is reschedule to a new node on node failure.
![image](https://user-images.githubusercontent.com/5108773/220728281-f333aa93-0ec4-420e-aebe-54f9c692ccf7.png)

**Ref:** 
- https://www.percona.com/blog/2021/01/20/drain-kubernetes-nodes-wisely/
- [AWS EBS Availability & Durability](https://bluexp.netapp.com/blog/comparing-aws-storage-slas-which-protects-you-best#:~:text=Amazon%20EBS%20volumes%20have%20annual,provide%20an%20availability%20of%2099.999%25.)

**Comment by nshangyiming** [comment]
@dengliu With this kind of architecture(k8s pod + pvc), i think what we want is don't trigger any repair action when FE lost hearbeat with BE because k8s will always run a new pod in relatively limited time, and keep other kind of repair action like fixing replicas with incomplete version, deleting redundant replicas because of balancing etc. To achieve that, the simplest solution i think is to increase the heartbeat timeout(`Config.heartbeat_timeout_second`) between FE and BE to a large value, at least larger than the maximum end-to-end reschedule time that k8s takes to deploy a new BE pod.

**Comment by dengliu** [comment]
Thanks @nshangyiming 
The idea sounds good to me.
I see the default value of `heartbeat_timeout_second` is `5`, which looks a bit confusing if it is `5` sec.
And there are also other configs related to heartbeat(see below), I am not sure if anything else needs to be updated.


```
heartbeat_timeout_second=5
heartbeat_retry_times=3
bdbje_heartbeat_timeout_second=30
heartbeat_mgr_threads_num=8
```

**Comment by nshangyiming** [comment]
@dengliu `heartbeat_timeout_second` parameter is used in conjunction with `heartbeat_retry_times`, and by default, the heartbeat timeout between the FE node and BE node is 5 seconds, if there are three consecutive timeouts, the BE node is considered to be not alive and FE will start to schedule replica repair task.

Because we use a global heartbeat manager to manage the heartbeats of FE leader node and all other types of nodes(FE follower/BE/broker), we need to use a thread pool to concurrently send heartbeats to these nodes. The default size of the thread pool is determined by the configuration of `heartbeat_mgr_threads_num`.

`bdbje_heartbeat_timeout_second` is used by the dependent bdbje module, we don't check aliveness based on this configuration, so we can ignore it in current situation.

**Comment by nshangyiming** [comment]
@dengliu I have checked the detail logic about `heartbeat_timeout_second`, if BE process quit completely, heartbeat request from FE will "timeout" immediately, but the checking interval of heartbeat thread on FE is based on `heartbeat_timeout_second`, so FE will still wait for 3*5 seconds before setting BE as dead. I think simply increase the value of `heartbeat_timeout_second` can meet your requirement. But to be noticed, the checking interval of heartbeat thread is initiated only on FE start, so change `heartbeat_timeout_second` after that won't affect this interval, so you can change it in FE conf file and restart FE to make it take effect.
