### ISSUE TITLE
Multiple FE pods cannot enter the ready state after being restarted.

### ISSUE THREAD

**Issue by HongofQSH** [StarRocks/starrocks-kubernetes-operator#73]
I started 3 FE pods with nfs storage. It works normally if I does not restart any pod.
When I restart one of the FE pods, it will recover to the ready state.
But when I execute the following command for restarting all FE pods simultaneously: 
[kubectl delete -f starrocks-fe.yaml].  At this time, the data in the NFS storage has been retained.
Then execute [kubectl apply -f starrocks-fe.yaml] , the state of fe-0 is in an unready state always.
I found that The FE pods must be started simultaneously, and the number of FE pods started must be the same as the number of FE pods started in the previous startup for the FE pods to start up normally. Otherwise, if only start up a single fe pod，it will remain in an unready state.
So，I tried to fix the source code of operator. In [func NewStatefulset], under [Spec: appv1.StatefulSetSpec], I added PodManagementPolicy: appv1.ParallelPodManagement, 
And also I modified the startup command in operator as following:
Before: 
                Command: []string{"/opt/starrocks/fe_entrypoint.sh"},
After: 	
var command = []string{
		"/bin/bash",
		"-c",
		"if [ -f \"/opt/starrocks/fe/meta/image/ROLE\" ]; then /opt/starrocks/fe/bin/start_fe.sh; else /opt/starrocks/fe_entrypoint.sh starrockscluster-sample-fe-service.starrocks; fi",
}
                 Command: command,

After the above changes, FE pods startup simultaneously, and the problem disappeared.
Can the author of Starrocks Operator tell me if my modification is correct?

**Comment by shileifu** [comment]
thanks for your contribution. but the method will not work. Fe use BDBJE to store metadata and select leader. 
 The follower fe listens to ports after the leader runs available.  the statefulset uses TCP port to check the pod's status.  when we use parallel mode start, it will be ok when the ROLE exists, but the first deployment will be Randomly available.
* use parallel mode and different start modes.
1) first deployment:
All fe pods start on concurrency. they may all start with the leader role. so the fe cluster is not available. 
2) clear and all restart:
when all pods use old PVC to restart we use the parallel mod and different start modes will restart success.
* use the OrderedReady policy and different start modes
1) first deployment:
it will be ok because all will use script `entrypoint.sh` to start.
2)clear and all restart
It is only available on the sequence number `0` pod is the leader of fe cluster. when other pods as leader, the `0` pod will not start successfully.
Very thanks for your issue, we will look into it. any questions we can communicate with each other.

**Comment by HongofQSH** [comment]
Thanks for your reply.
>first deployment:
>All fe pods start on concurrency. they may all start with the leader role. so the fe cluster is not available.
At the first deployment, all fe pods start on concurrency. FEs will communicate each other, and elect only one leader(master). I tested many times, it looks fine. But I do not know if there is any other side-effect of the parallel start.

**Comment by shileifu** [comment]
the mystery is fe_entrypoint.sh.  the statefulset control's pods have numbers. when the sequence 0 pod start waits 60s, and other pods wait 120s.

**Comment by HongofQSH** [comment]
If we do not use parallet start, the FE startup process will be like this.
At the first deployment,  
    Pod 0 starts.
    Wait for several tens of seconds......
   If there is not any other leader, Pod 0 becomes leader and enters the ready state.
   Other pods start one by one.
At the second deployment
   Pod 0 starts.
   Pod 0 itself is leader, but it will wait for the startup of other followers......
   Due to other FEs starting only after pod 0 enters ready state, it will result in a deadlock.
   Pod 0 not ready, time out, restart.
   Pod 0 not ready, time out, restart.
  ......

"The biggest issue is that during the second deployment, the Leader cannot detect the existence of other followers and therefore cannot start properly. To enable the Leader to start, all registered followers in the starock cluster must be started without waiting for Leader's ready state. 
This issue does not seem to be related to fe_entrypoint.sh."

**Comment by shileifu** [comment]
yes, we talked about it, we think your proposal about parallel start fe is right. we will do it in next version.

**Comment by HongofQSH** [comment]
OK, that's right. And, don't forget to change the startup command of the second deployment which I have pasted at first. Perhaps modifying the fe_entrypoint.sh file would be a better option than modifying the operator.

**Comment by shileifu** [comment]
the new version v1.6 has been supported, thanks for your contributions.
